openapi: 3.0.3
info:
  title: sandbox-api
  description: This API is a sandbox for testing purposes
  version: 0.0.1
servers:
  - url: 'https'
tags:
  - name: users
    description: User operations
  - name: articles
    description: Article operations
paths:
  /users:
    $ref: './paths/users.yaml#/users'
  /articles:
    $ref: './paths/articles.yaml#/articles'
